from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from django.urls import path

from .views import (
    SignupView,
    UserProfileView,
    GuideView,
    TouristView,
    EventManagerView,
    TourView,
    TouristCompletedTourView,
    EventView,
    EventCompletedView,
)

urlpatterns = [
    path(
        "login/",
          TokenObtainPairView.as_view(),
            name="token_obtain_pair"
            ),
    path(
        "token/refresh/",
          TokenRefreshView.as_view(),
            name="token_refresh"
            ),
    path(
        "signup/",
          SignupView.as_view(),
            name="signup"
            ),
    path(
        "profile/",
          UserProfileView.as_view(),
            name="profile"
            ),
    path(
        "guides/",
          GuideView.as_view(),
            name="guides-list"
            ),
    path(
        "guides/<int:pk>/",
          GuideView.as_view(),
            name="guide-detail"
            ),
    path(
        "tourists/",
          TouristView.as_view(),
            name="tourists-list"
            ),
    path(
        "tourists/<int:pk>/",
          TouristView.as_view(),
            name="tourist-detail"
            ),
    path(
        "event-managers/",
          EventManagerView.as_view(),
            name="event-managers-list"
            ),
    path(
        "event-managers/<int:pk>/",
        EventManagerView.as_view(),
        name="event-manager-detail",
    ),
    path(
        "tours/",
          TourView.as_view(),
            name="tours-list"
        ),
    path(
        "tours/<int:pk>/",
          TourView.as_view(),
            name="tour-detail"
        ),
    path(
        "completed-tours/",
        TouristCompletedTourView.as_view(),
        name="completed-tours-list",
    ),
    path(
        "completed-tours/<int:pk>/",
        TouristCompletedTourView.as_view(),
        name="completed-tour-detail",
    ),
    path(
        "events/",
          EventView.as_view(),
            name="events-list"
            ),
    path(
        "events/<int:pk>/",
          EventView.as_view(),
            name="event-detail"
            ),
    path(
        "completed-events/",
          EventCompletedView.as_view(),
            name="completed-events-list"
    ),
    path(
        "completed-events/<int:pk>/",
        EventCompletedView.as_view(),
        name="completed-event-detail",
    ),
]
