# Generated by Django 5.0.6 on 2024-06-19 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_remove_event_event_manager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('photo1', models.ImageField(blank=True, default='events/default.jpg', null=True, upload_to='events/')),
                ('photo2', models.ImageField(blank=True, default='events/default.jpg', null=True, upload_to='events/')),
                ('photo3', models.ImageField(blank=True, default='events/default.jpg', null=True, upload_to='events/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='events/videos/')),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('event_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.eventmanager')),
            ],
        ),
        migrations.CreateModel(
            name='EventCompleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('event_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.eventmanager')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tourist')),
            ],
        ),
        migrations.CreateModel(
            name='EventManagerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_manager_ratings', to='events.event')),
                ('eventmanager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_manager_ratings', to='accounts.eventmanager')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_manager_ratings', to='accounts.tourist')),
            ],
        ),
    ]
