# Generated by Django 5.0.6 on 2024-06-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pfp',
            field=models.ImageField(blank=True, default='user_avatar/default.jpg', null=True, upload_to='user_avatar/'),
        ),
    ]
