# Generated by Django 5.0.6 on 2024-06-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuserprofile_guide_tourist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuserprofile',
            name='rating',
        ),
        migrations.AddField(
            model_name='guide',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
