# Generated by Django 5.0.6 on 2024-06-18 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuserprofile_rating_guide_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='rating',
        ),
        migrations.CreateModel(
            name='GuideRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='accounts.guide')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tourist')),
            ],
        ),
    ]
