# Generated by Django 5.0.6 on 2024-06-18 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_guide_rating_guiderating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.guide')),
            ],
        ),
        migrations.CreateModel(
            name='TouristCompletedTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tour')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tourist')),
            ],
        ),
    ]
