# Generated by Django 5.0.6 on 2024-06-18 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_tour_touristcompletedtour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('photo1', models.ImageField(blank=True, default='events/default.jpg', null=True, upload_to='events/')),
                ('photo2', models.ImageField(blank=True, default='events/default.jpg', null=True, upload_to='events/')),
                ('photo3', models.ImageField(blank=True, default='events/default.jpg', null=True, upload_to='events/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='events/videos/')),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='customuserprofile',
            name='is_event_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guiderating',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.touristcompletedtour'),
        ),
        migrations.AddField(
            model_name='touristcompletedtour',
            name='guide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.guide'),
        ),
        migrations.CreateModel(
            name='EventManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_events', models.IntegerField(default=0)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuserprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EventCompleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.event')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tourist')),
                ('event_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.eventmanager')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.eventmanager'),
        ),
        migrations.CreateModel(
            name='EventManagerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.eventcompleted')),
                ('eventmanager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='accounts.eventmanager')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tourist')),
            ],
        ),
    ]
