# Generated by Django 5.0.6 on 2024-06-19 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_event_customuserprofile_is_event_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_manager',
        ),
        migrations.RemoveField(
            model_name='eventcompleted',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventcompleted',
            name='event_manager',
        ),
        migrations.RemoveField(
            model_name='eventcompleted',
            name='tourist',
        ),
    ]
