# Generated by Django 5.0.6 on 2024-06-19 04:12

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_event_event_manager_and_more'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmanagerrating',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventcompleted'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=accounts.models.generate_unique_username, max_length=150, unique=True),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventCompleted',
        ),
    ]
