# Generated by Django 5.0.6 on 2024-06-19 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_eventmanagerrating_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='guide',
        ),
        migrations.RemoveField(
            model_name='touristcompletedtour',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='touristcompletedtour',
            name='guide',
        ),
        migrations.RemoveField(
            model_name='touristcompletedtour',
            name='tourist',
        ),
    ]
