# Generated by Django 5.0.6 on 2024-06-19 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_tour_guide_remove_touristcompletedtour_tour_and_more'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiderating',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.touristcompletedtour'),
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
        migrations.DeleteModel(
            name='TouristCompletedTour',
        ),
    ]
